
services:
  web:
    image: ilangimel/bleachdle-web-app # Specify the image if you're using a pre-built one instead of building it
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - DB_HOST=${DB_HOST}  # Points to the db service name defined below
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - API_URL=${API_URL}
    depends_on:
      - db  # Ensures that the web service waits for the db to start
    command: ["flask", "run", "--host=0.0.0.0"]  # To make sure Flask listens on all interfaces

  db:
    image: mysql:8 
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:



